name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repo-token: ${{ secrets.G_TOKEN }}
      - name: Run a one-line script
        run: ls -la
      - name: Run a multi-line script
        run: |
          pwd
          whoami
      - run: |
          date > generated.txt
          git config user.name BobTheBuilder
          git config user.email raw@dopehosting.net
          git add .
          git commit -m "ip list refresh"
          git push https://${{ secrets.G_USER }}:${{ secrets.G_PASSWORD }}@github.com/${{ github.repository }} --all
